### ISSUE TITLE
feature request:volume

### ISSUE THREAD

**Issue by Ndrocchietto** [Stonks/tickers#1]
Please consider volume, thanks for your effort for the community anyway.

**Comment by irelandmi** [comment]
++ this ^

**Comment by GN** [comment]
@irelandmi @Ndrocchietto 

Sorry for the delay! (also sorry for the bot being down), I've added both volume and 50 moving average data and fixed the bot being down for the last week or two. 

Enjoy :)

**Comment by Ndrocchietto** [comment]
Cool stuff Gennaro, as I am neapolitan as well i give you a virtual sfogliatella thanks:)

**Comment by GN** [comment]
@Ndrocchietto Been a couple years since I made some, but these are from the last batch I made when I was in college!


![Screenshot_20230730-104647.png](https://github.com/Stonks/tickers/assets/25604170/b90a5059-9e3b-4a7e-a0fb-1b19639b3eb3)

**Comment by Ndrocchietto** [comment]
awesome yea I saw  now you are in the states, when you go to Naples go to  [Attanasio](https://www.napolike.it/turismo/sfogliatelle-napoletane/)
