### ISSUE TITLE
Inaccurate data

### ISSUE THREAD

**Issue by redrossa** [Stonks/tickers#3]
First of all, I truly want to thank you so much for this project. However, for some of the tickers I scrutinized, the prices are off (not just minor cents, but mostly a couple units of dollars and even up to tens) compared to Alpaca data. May I please get the URL source you use?

**Comment by Ndrocchietto** [comment]
please would you provide an example of differences with Alpaca, maybe we can see with other data sources

**Comment by GN** [comment]
can you provide examples of the data discrepancies that you've encountered? 

Thanks!
